### ISSUE TITLE
Support for a Windows Server AWS EC2 instance deployment using Terraform

### ISSUE THREAD

**Issue by likamrat** [likamrat/azure_arc#7]
### Description
Support for a lightweight Windows Server AWS EC2 instance deployment with Arc connectivity using Terraform

### Implementation Requirments

- Lightweight VM for fast provisioning
- Parameterize deployment using Terraform
- Azure Arc connectivity instructions
- Detailed README
- Reference in the main README

### Supporting Docs

[Please refer to the supported Azure Arc supported OS](https://docs.microsoft.com/en-us/azure/azure-arc/servers/overview)

**Comment by youf05** [comment]
There is a blocking issue with Terraform AWS provider - https://github.com/hashicorp/terraform/issues/24970
This will make it clunky for users to create Windows instances because they will need to create keys using a different method compared to the other quickstart guides which use ssh-keygen. Parking this enhancement for now.
